name: CI & Allure Report

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize, reopened, ready_for_review ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  test:
    name: Run Tests (Poetry, Playwright, Docker)
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/java-21-openjdk-amd64
      POETRY_VIRTUALENVS_CREATE: false
      PW_HEADLESS: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: pip install poetry

      - name: Cache Poetry packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-3.13-${{ hashFiles('niffler_e_2_e_tests_python/poetry.lock') }}
          restore-keys: |
            poetry-3.13-

      - name: Install dependencies
        working-directory: ./niffler_e_2_e_tests_python
        run: poetry install --no-root

      - name: Install Playwright browsers (with system deps)
        working-directory: ./niffler_e_2_e_tests_python
        run: poetry run playwright install --with-deps

      - name: Add local DNS aliases for *.niffler.dc
        run: |
          echo "127.0.0.1 auth.niffler.dc gateway.niffler.dc frontend.niffler.dc userdata.niffler.dc" | sudo tee -a /etc/hosts

      - name: Build & start Docker environment
        working-directory: .
        run: |
          chmod +x ./docker-compose-dev.sh
          ./docker-compose-dev.sh

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev
          allure --version

      - name: Run tests (Allure results)
        working-directory: ./niffler_e_2_e_tests_python
        run: |
          chmod +x ./run_allure.sh
          ./run_allure.sh --workers auto --dist loadfile
        continue-on-error: true

      - name: Upload Allure results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: niffler_e_2_e_tests_python/allure-results

  build-report:
    name: Generate Allure HTML
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: ./allure-results

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev
          allure --version

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: allure-report

  generate-report:
    name: Generate & Publish Allure Report
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    environment:
      name: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: ./allure-results

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev
          allure --version

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4